"""
Writing Agent
=============
Takes all research artifacts (literature review, experiment design, code results,
evaluation) and generates a complete research paper with all sections.
Stores each section as a DraftSection record.
"""
from __future__ import annotations

import logging
from uuid import UUID

from sqlalchemy.orm import Session

from app.models.pipeline import PipelineRun
from app.models.project import Project, ResearchQuestion
from app.models.writing import DraftSection
from app.services import llm_service, pipeline_service

log = logging.getLogger(__name__)

SECTIONS = [
    ("abstract", "Abstract"),
    ("introduction", "Introduction"),
    ("related_work", "Related Work"),
    ("methodology", "Methodology"),
    ("experiments", "Experiments"),
    ("results", "Results and Discussion"),
    ("conclusion", "Conclusion"),
]

SECTION_SYSTEM = """\
You are an expert academic writer. Write the {section_name} section of a
research paper given the context below.

Rules:
- Write in formal academic style
- Be specific and cite findings from the provided data
- Use LaTeX-style citations like \\cite{{author2024}}
- Length: {length_guide}
- Return ONLY the section text in Markdown format (no extra commentary)
"""

LENGTH_GUIDES = {
    "abstract": "150-250 words",
    "introduction": "500-800 words, covering motivation, problem, contributions",
    "related_work": "400-700 words, organized by themes",
    "methodology": "500-800 words, detailed enough to reproduce",
    "experiments": "400-600 words, covering setup, datasets, baselines",
    "results": "500-800 words, discussing findings, tables, ablations",
    "conclusion": "200-400 words, summarizing contributions and future work",
}


async def run(db: Session, project_id: UUID, run_record: PipelineRun) -> None:
    """Generate all paper sections from research artifacts."""
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise ValueError(f"Project {project_id} not found")

    pipeline_service.start_run(db, run_record)
    pipeline_service.append_log(db, run_record, "✍️ Writing agent started")

    # Gather all context
    context = _build_context(db, project_id, project)

    sections_written = []
    for section_key, section_title in SECTIONS:
        pipeline_service.append_log(db, run_record, f"📝 Writing: {section_title}…")

        system_prompt = SECTION_SYSTEM.format(
            section_name=section_title,
            length_guide=LENGTH_GUIDES.get(section_key, "300-500 words"),
        )

        content = await llm_service.chat([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": context},
        ], temperature=0.5, max_tokens=4096)

        # Upsert DraftSection
        existing = (
            db.query(DraftSection)
            .filter(
                DraftSection.project_id == project_id,
                DraftSection.section_key == section_key,
            )
            .first()
        )
        if existing:
            existing.content_markdown = content
            existing.title = section_title
            existing.revision_note = "Auto-generated by Writing Agent"
        else:
            section = DraftSection(
                project_id=project_id,
                section_key=section_key,
                title=section_title,
                content_markdown=content,
                revision_note="Auto-generated by Writing Agent",
            )
            db.add(section)

        sections_written.append(section_key)

    db.commit()

    pipeline_service.complete_run(
        db, run_record,
        result_summary=f"Generated {len(sections_written)} paper sections: {', '.join(sections_written)}",
        result_data={"sections": sections_written},
    )
    pipeline_service.append_log(db, run_record, "✅ Paper writing complete")


def _build_context(db: Session, project_id: UUID, project: Project) -> str:
    """Build a comprehensive context string from all available artifacts."""
    parts = [f"Paper title: {project.title}"]

    if project.short_idea:
        parts.append(f"Core idea: {project.short_idea}")

    # Research question
    rq = (
        db.query(ResearchQuestion)
        .filter(ResearchQuestion.project_id == project_id)
        .first()
    )
    if rq:
        parts.append(f"Research question: {rq.main_question}")
        if rq.hypotheses:
            parts.append(f"Hypotheses: {rq.hypotheses}")
        if rq.novelty_claim:
            parts.append(f"Novelty claim: {rq.novelty_claim}")

    # Literature review synthesis
    from app.services.agents import _get_latest_run_result
    lit_synthesis = _get_latest_run_result(db, project_id, "literature")
    if lit_synthesis:
        parts.append(f"\n--- Literature Review ---\n{lit_synthesis}")

    # Experiment design
    from app.models.experiment import ExperimentPlan
    plan = (
        db.query(ExperimentPlan)
        .filter(ExperimentPlan.project_id == project_id)
        .first()
    )
    if plan:
        parts.append(
            f"\n--- Experiment Design ---\n"
            f"Objective: {plan.objective}\n"
            f"Hypotheses: {plan.hypotheses}\n"
            f"Baselines: {plan.baselines}\n"
            f"Datasets: {plan.datasets}\n"
            f"Metrics: {plan.metrics}\n"
            f"Ablations: {plan.ablations}"
        )

    # Code execution results
    from app.services.agents import _get_latest_run_data
    code_data = _get_latest_run_data(db, project_id, "code")
    if code_data:
        parts.append(
            f"\n--- Experiment Output ---\n"
            f"{code_data.get('stdout', '')[:5000]}"
        )

    # Evaluation
    eval_data = _get_latest_run_data(db, project_id, "evaluation")
    if eval_data:
        import json
        parts.append(
            f"\n--- Evaluation Results ---\n"
            f"{json.dumps(eval_data, indent=2)[:5000]}"
        )

    return "\n\n".join(parts)
